
CREATE TABLE PATIENT (
    NUM_PATIENT     INT AUTO_INCREMENT PRIMARY KEY,
    NOM_PERS        VARCHAR(50) NOT NULL,
    PRENOM_PERS     VARCHAR(50) NOT NULL,
    DATE_NAIS       DATE NOT NULL,
    POIDS           DECIMAL(5,2),
    TAILLE          DECIMAL(5,2),
    NTEL            VARCHAR(20),
    ADRESSE         VARCHAR(150),
    NUM_MEDECIN     INT NOT NULL,
    FOREIGN KEY (NUM_MEDECIN) REFERENCES MEDECIN(NUM_MEDECIN)
);

CREATE TABLE VISITE (
    NUM_VISITE      INT AUTO_INCREMENT PRIMARY KEY,
    DATE_VISITE     DATE NOT NULL,
    MOTIF           VARCHAR(200),
    LIEU            VARCHAR(20) NOT NULL,
    NUM_PATIENT     INT NOT NULL,
    NUM_MEDECIN     INT NOT NULL,
    FOREIGN KEY (NUM_PATIENT) REFERENCES PATIENT(NUM_PATIENT),
    FOREIGN KEY (NUM_MEDECIN) REFERENCES MEDECIN(NUM_MEDECIN)
);

CREATE TABLE ORDONNANCE (
    NUM_ORDONNANCE  INT AUTO_INCREMENT PRIMARY KEY,
    DATE_ORDONNANCE DATE NOT NULL,
    NUM_VISITE      INT NOT NULL UNIQUE,
    FOREIGN KEY (NUM_VISITE) REFERENCES VISITE(NUM_VISITE)
);

CREATE TABLE DEMANDE_ANALYSE (
    NUM_DEMANDE     INT AUTO_INCREMENT PRIMARY KEY,
    DATE_DEMANDE    DATE NOT NULL,
    RESULTAT_RECU   BOOLEAN DEFAULT FALSE,
    NUM_VISITE      INT NOT NULL,
    FOREIGN KEY (NUM_VISITE) REFERENCES VISITE(NUM_VISITE)
);

CREATE TABLE MEDICAMENT (
    NUM_MEDICAMENT  INT AUTO_INCREMENT PRIMARY KEY,
    NOM_MEDICAMENT  VARCHAR(100) NOT NULL,
    CATEGORIE       VARCHAR(50),
    DESCRIPTION     VARCHAR(255)
);

CREATE TABLE PRESCRIT (
    NUM_ORDONNANCE          INT,
    NUM_MEDICAMENT          INT,
    NB_PRISES               INT,
    NB_DOSES_PAR_PRISE      INT,
    FREQUENCE_JOURNALIERE   INT,
    DUREE_TRAITEMENT        INT,
    PRIMARY KEY (NUM_ORDONNANCE, NUM_MEDICAMENT),
    FOREIGN KEY (NUM_ORDONNANCE) REFERENCES ORDONNANCE(NUM_ORDONNANCE),
    FOREIGN KEY (NUM_MEDICAMENT) REFERENCES MEDICAMENT(NUM_MEDICAMENT)
);

CREATE TABLE MALADIE (
    NUM_MALADIE     INT AUTO_INCREMENT PRIMARY KEY,
    NOM_MALADIE     VARCHAR(100) NOT NULL,
    DESCRIPTION     VARCHAR(255)
);

CREATE TABLE PATIENT_MALADIE (
    NUM_PATIENT     INT,
    NUM_MALADIE     INT,
    DATE_DIAGNOSTIC DATE,
    PRIMARY KEY (NUM_PATIENT, NUM_MALADIE),
    FOREIGN KEY (NUM_PATIENT) REFERENCES PATIENT(NUM_PATIENT),
    FOREIGN KEY (NUM_MALADIE) REFERENCES MALADIE(NUM_MALADIE)
);

CREATE TABLE ALLERGIE (
    NUM_ALLERGIE     INT AUTO_INCREMENT PRIMARY KEY,
    LIBELLE_ALLERGIE VARCHAR(100) NOT NULL
);

CREATE TABLE PATIENT_ALLERGIE (
    NUM_PATIENT     INT,
    NUM_ALLERGIE    INT,
    OBSERVATION     VARCHAR(255),
    PRIMARY KEY (NUM_PATIENT, NUM_ALLERGIE),
    FOREIGN KEY (NUM_PATIENT) REFERENCES PATIENT(NUM_PATIENT),
    FOREIGN KEY (NUM_ALLERGIE) REFERENCES ALLERGIE(NUM_ALLERGIE)
);

CREATE TABLE SEJOUR (
    NUM_SEJOUR      INT AUTO_INCREMENT PRIMARY KEY,
    NOM_CENTRE      VARCHAR(100) NOT NULL,
    DATE_DEBUT      DATE NOT NULL,
    DATE_FIN        DATE,
    OPERATION       VARCHAR(255),
    NUM_PATIENT     INT NOT NULL,
    FOREIGN KEY (NUM_PATIENT) REFERENCES PATIENT(NUM_PATIENT)
);
